### PR TITLE
Moving to a runtime agnostic library

### LINKED ISSUE #2: Question: any way to make it runtime agnostic?
I see a lot of libraries starting to move to async/await, but being dependent on specific runtimes (either async-std or tokio) and this can become a mess when developers starts to need different libraries depending on different runtimes...

Also are you planning to merge it with the synchronous version or maintaining both in parallel?

### PR DESCRIPTION
**Pull request by augustocdias**
I've found out that the only required change to make it runtime agnostic is split the transport layer to a separate crate.

I've made local crates for them and I'm planning to implement one for tokio as well.

Right now the only issue I have to check is in the `frame_channel` module where the write in line 55 was being called directly and the compiler was not complaining about not consuming the future, even though the return from write method from async std is a future. I changed to check the poll write result, but I'm not 100% sure about this.

I also ran cargo fmt in the project (I hope you don't mind).

There was a single API change from all this work which is the way the session is created. Instead of passing an address, now it is needed to pass a transport object. If someone wants to implement their own runtime, they have to implement a transport for the library (which consists of implementing the trait `CDRSTransport`). 

Closes #2

### CODE REVIEW

**Comment by augustocdias** [comment]
I managed to run the example but I cannot run the tests. I tried with my branch and yours and I get the same result... Is there a special setup that I have to do to make it work?


```running 2 tests
test speculate_0::keyspace::test_should_create_a_new_keyspace ... test speculate_0::keyspace::test_should_create_a_new_keyspace has been running for over 60 seconds
test speculate_0::keyspace::test_should_remove_a_keyspace ... test speculate_0::keyspace::test_should_remove_a_keyspace has been running for over 60 seconds
```

**Comment by AlexPikalov** [comment]
Hi @augustocdias ,
Thank you for the submission! I'll needs some time to get through this PR.

Regarding problems with tests. Have you tried to run them with `CDRS_LOCAL_TEST_DB=cassandra` env variable?

Perhaps I need to seriously consider investing more time in docs. 🙂

**Comment by augustocdias** [comment]
Yes. I set the env var... I'll start writing the transport for tokio so we can be sure that this solution works.

**Comment by AlexPikalov** [comment]
Sounds good 👍

**Comment by augustocdias** [comment]
Hey, I've added the code for `tokio` and I managed to make it run with the basic test.
I also did some changes in the tests that you wrote to cover both tokio and async std.

**Comment by augustocdias** [comment]
The tests are failing because of this error: 

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 469dfa50-92ac-11ea-a6af-7b648eefb31e; expected 46985500-92ac-11ea-a6af-7b648eefb31e)
```

Is it something I changed?

**Comment by AlexPikalov** [comment]
@augustocdias weird, let me check it locally please

**Pull request closed without merging**
